superlinear-ai/raglite

- poetry.lock
- pyproject.toml
- src/raglite/_markdown.py
Changes:
- Upgrade pdftext minimum version so that it uses ONNX models instead of pickled scikit-learn models (which may not be compatible with the installed version of scikit-learn).
> fix: upgrade pdftext

- README.md
- src/raglite/_split_chunks.py
- tests/test_split_chunks.py
This PR fixes or improves the following:
1. If there are 0 or 1 sentences, exit early with 1 chunk.
2. If there total length of all sentences is less than the chunk max size, exit early with 1 chunk.
3. The discourse vector is now normalised to unit length.
4. The discourse vector is only removed if it would not lead to all-zero embeddings (which can happen for an array of identical sentences).
5. Preconditions are verified at the beginning.
> fix: fix optimal chunking edge cases

- src/raglite/_database.py
- src/raglite/_litellm.py
- src/raglite/_rag.py
Related to #43, where the number of embedding dimensions is missing, I am adding a fallback mechanism that embeds a dummy sentence in order to infer the number of dimensions if they are not available in the configuration.
> fix: fallback for calculation embedding dimensions if not available

- src/raglite/_extract.py
- src/raglite/_litellm.py
- src/raglite/_query_adapter.py
- tests/test_extract.py
two small bugs i noted, which this PR should fix.
1) OpenAI models (and probably more non llama-cpp models) fail in the extract step, since there is a schema key in response format and the system prompt is formatted as a tuple.
2) If you have already created a query adapter, if you then try to updated it again (after generating more evals f.e.), sqlalchemy throws an error. This is because you are trying to add the same key to the metadata_ dir. The fix changes it in-place instead and uses flag_modified to make sure SQLAlchemy updates accordingly when commiting.
> fix: extract_with_llm model compatibility and query adapter updates

- README.md
- src/raglite/__init__.py
- src/raglite/_chainlit.py
- src/raglite/_database.py
- src/raglite/_eval.py
- src/raglite/_extract.py
- src/raglite/_insert.py
- src/raglite/_rag.py
- src/raglite/_search.py
- src/raglite/_typing.py
- tests/test_rag.py
- tests/test_search.py
Several improvements:
- We return the document id in the context to make it available to the model. #50
- Better reconstruction of segments considering headings hierarchy 
- Fix order of segments. We use the sum of the reciprocal ranks of the chunks by default, while allowing passing a scoring function.
- Now we write the context in the user prompt, but we can configure to pass it in the system prompt or in a separate system prompt. #49
> feat: support prompt caching and apply Anthropic's long-context prompt format

- README.md
- docker-compose.yml
- poetry.lock
- pyproject.toml
- src/raglite/_config.py
- src/raglite/_database.py
- src/raglite/_litellm.py
- src/raglite/_search.py
- tests/conftest.py
- tests/test_rerank.py
Changes:
- Add a workaround for #24 to increase the embedder's context size from 512 to a user-definable size.
- Increase the default embedder context size to 1024 tokens (more degrades bge-m3's performance).
- Upgrade llama-cpp-python to the latest version.
- More robust testing of rerankers with Kendall's rank correlation coefficient.
- Optimise pgvector's settings.
- Offer better control of oversampling in hybrid and vector search.
- Upgrade to the PostgreSQL 17.
> feat: improve late chunking and optimize pgvector settings

- src/raglite/_eval.py
Use the configured embedder with Ragas
> fix: support embedding with LiteLLM for Ragas

- src/raglite/_eval.py
- src/raglite/_extract.py
- tests/test_extract.py
Deal with OpenAI idiosyncrasies regarding JSON schemas.
> fix: add and enable OpenAI strict mode

- src/raglite/_litellm.py
Reduce the log level of httpx to maintain a clean output and only inform users of events when necessary.
> style: reduce httpx log level

- README.md
- poetry.lock
- pyproject.toml
- src/raglite/_chainlit.py
- src/raglite/_database.py
- src/raglite/_extract.py
- src/raglite/_litellm.py
- src/raglite/_rag.py
- src/raglite/_search.py
- tests/conftest.py
- tests/test_extract.py
- tests/test_rag.py
Changes:
- Add support for tool use to the llama.cpp LiteLLM integration.
- The `rag` or `async_rag` functions now update the message history with tool use and the assistant response.
- Let LLM choose whether to retrieve context through tool use. Details:
- Tool use is skipped if RAG context is already provided.
- Llama.cpp models cannot stream the response with `tool_choice="auto"` (which lets the LLM choose whether or not to call a tool), so we add a workaround that forces tool use but lets them skip tool execution with a `skip=True` argument.
- To help llama.cpp models plan their tool use response, the final message is extended with the tools' JSON schema.
- Fix registering of llama.cpp model_info with LiteLLM.
- Improve RAG generation test cases.
- Improve LLM-embedder test coverage.
> feat: let LLM choose whether to retrieve context

- README.md
- poetry.lock
- pyproject.toml
- src/raglite/_cli.py
- src/raglite/_config.py
- src/raglite/_database.py
- src/raglite/_mcp.py
Changes:
1. Add an MCP server with a `search_knowledge_base` tool and a `kb` prompt.
2. Add the ability to install and run the MCP server with the CLI, based on [FastMCP](https://github.com/jlowin/fastmcp)'s implementation.
3. Hoist the RAGLite configuration in the CLI to the top-level `raglite` command.
4. Improve the default location of the SQLite database with `platformdirs`.
5. Improve the default rerankers cache directory with `platformdirs`.
https://github.com/user-attachments/assets/3a597a17-874e-475f-a6dd-cd3ccf360fb9
https://github.com/user-attachments/assets/a303ed4a-54cd-45ea-a2b5-86e086053aed
> feat: add MCP server

- src/raglite/_extract.py
> docs: fix typo in _extract.py

- src/raglite/_split_sentences.py
- tests/test_split_sentences.py
Changes:
- Improve sentence splitting with better treating of Markdown headings. The start and end of a Markdown heading are now properly marked as the start of a new sentence, while its body is marked as not containing any sentence boundaries. These are supplied as hints to spaCy to improve overall output quality.
- Sentence splitting is now explicitly covered by tests.
> feat: improve sentence splitting

- src/raglite/_chatml_function_calling.py
- src/raglite/_litellm.py
- src/raglite/_mcp.py
- src/raglite/_rag.py
- tests/conftest.py
- tests/test_chatml_function_calling.py
- tests/test_rag.py
Changes:
1. ✨ Enable streaming tool use for llama-cpp-python models (see below for details). The result is a more simple `rag` and `async_rag` implementation that opens the door to Agentic RAG and user-defined tools.
2. ✨ Update the `query` parameter description to require that it is a single-faceted question (i.e., a non-compound question) to encourage parallel function calling for compound questions.
3. ✅ Add fairly thorough tests for both `rag` and the improved `chatml-function-calling` chat handler.
Changes to llama-cpp-python's `chatml-function-calling` chat handler:
1. General:
a. ✨ If no system message is supplied, add an empty system message to hold the tool metadata.
b. ✨ Add function descriptions to the system message so that tool use is better informed (fixes …
> feat: add streaming tool use to llama-cpp-python

- src/raglite/_litellm.py
Attempt to fix the CI from failing because of a lack of memory by conditionally enabling the `LlamaRAMCache`.
> fix: conditionally enable `LlamaRAMCache`

- poetry.lock
- pyproject.toml
LiteLLM v1.56.10 breaks `get_model_info` for custom providers: https://github.com/BerriAI/litellm/issues/7575.
This PR excludes v1.56.10 and up until they release a new version that fixes that issue.
> fix(deps): exclude litellm versions that break get_model_info

- src/raglite/_chatml_function_calling.py
This PR removes an unnecessary stop sequence for llama-cpp-python models, which could lead to a superfluous character being printed at the end of the LLM response.
> fix: remove unnecessary stop sequence

- pyproject.toml
- src/raglite/__init__.py
Main offenders that make `import raglite` slow:
1. `import litellm` takes ~1s (https://github.com/BerriAI/litellm/issues/7605).
2. Loading a `BaseSettings` takes ~1s.
This PR changes the exports so that `BaseSettings` are only loaded when actually using the CLI. After this PR, `import raglite` should be reduced to about ~1.9s.
> feat: make importing faster

- README.md
- src/raglite/_database.py
- src/raglite/_insert.py
This PR introduces the ability to directly pass markdown content as input when inserting documents into the database. Previously, only file paths (e.g., PDF) were supported, but with this change, users can now input a markdown string directly, making the process more flexible.
**Changes:**
1. New Method: Created a method to generate a Document object from markdown content.
2.  Modified insert_document Function: Updated the insert_document function to include markdown content.
3. Updated the Readme to explain the new feature
This change improves the workflow for users who need to insert markdown content directly, without requiring it to be written to a file first.
**Testing:**
This PR has been tested locally with a local setup. 
Markdown data is correctly stored in the local sqlite …
> feat: add ability to directly insert Markdown content into the database

- poetry.lock
- pyproject.toml
- src/raglite/_chatml_function_calling.py
- src/raglite/_config.py
- src/raglite/_embed.py
- src/raglite/_lazy_llama.py
- src/raglite/_litellm.py
- tests/test_chatml_function_calling.py
This PR converts `llama-cpp-python` from an installation-time dependency to an optional, runtime, dependency. Previously, installing Raglite involved building a wheel for `llama-cpp-python`, which can fail in some cases, as described in issue #94. It is now possible to install `llama-cpp-python` by running `pip install raglite[llama-cpp-python]`. In the absence of an API-KEY for an API-based LLM provider, Raglite still fails over to `llama-cpp-python` to run locally-hosted LLMs, but now gracefully errors out if `llama-cpp-python` is not installed thanks to a lazy loading of `llama-cpp-python`.
Changes:
- Created of a `_lazy_llama.py` file that lazily loads all. 
- Updated files that required `llama-cpp-python` to leverage the above-mentioned lazy loading mechanism.
> feat: make llama-cpp-python an optional dependency

- src/raglite/_chatml_function_calling.py
- src/raglite/_cli.py
- src/raglite/_eval.py
- src/raglite/_lazy_llama.py
- src/raglite/_litellm.py
- src/raglite/_markdown.py
- tests/test_chatml_function_calling.py
- tests/test_lazy_llama.py
Changes:
1. Replace `ImportError` with a more specific `ModuleNotFoundError` (which is also an `ImportError`).
2. Lazily raise `ModuleNotFoundError` for attributes and submodules imported from llama-cpp-python (the current behaviour raises that error on import).
3. Add a test to verify that RAGLite can be imported without llama-cpp-python and that it only lazily raises a `ModuleNotFoundError` if you do depend on llama-cpp-python.
CC @rchretien
> fix: lazily raise module not found for optional deps

- src/raglite/_split_chunks.py
when a sentence is length max_size (which i guess happens every time there are sentence with length greater than max_size due to max_len in sentence splitter), the chunking fails without clear error on the assert idx > i, since np.searchsorted will return idx = i.
We can use side="right" instead, because we do actually want to find the 'right-most' index as the docs say (because that will yield fewer constraints), and it also solves the off-by-one issue.
> fix: fix chunking of single-sentence chunks

- src/raglite/_embed.py
- src/raglite/_insert.py
Currently, chunks are windowed based on config.embedder_sentence_window_size. This PR refactors _embed and adds an embed_text function we can use for cases where we don't want to accidentally use the embed_sentences functionality, like windowing. It then uses this function in _insert to prevent the windowing of chunks.
Additionally, headings are not incorporated in chunk embeddings. This PR fixes that as well by using the chunk_record.content that has the extracted header, instead of using the input list of chunks
> fix: incorporate headings and prevent windowing chunks

- src/raglite/_insert.py
Adds a argument in insert_document of metadata that gets passed to all chunks built from the file
> feat: add metadata at the document level

- .github/workflows/test.yml
- README.md
- pyproject.toml
- src/raglite/_chatml_function_calling.py
- src/raglite/_config.py
- src/raglite/_litellm.py
- tests/conftest.py
- tests/test_chatml_function_calling.py
This PR adds support for [Qwen3](https://qwenlm.github.io/blog/qwen3/) and reasoning tool use. [Qwen3 8B in 4bit is currently Simon Willison's favourite model](https://x.com/simonw/status/1918451927207325774). Reasoning can be disabled by adding `/no_think` to any message.
Changes:
1. Upgrade llama-cpp-python to >=0.3.9, which has a newer version of llama.cpp that supports Qwen3.
2. Replace Llama 3.1 8B and 3.2 3B with Qwen3 8B and 4B, respectively.
3. Recommend using Unsloth GGUF's in the README. They recently introduced [Dynamic 2.0 GGUFs](https://unsloth.ai/blog/dynamic-v2) and are probably the highest quality quants available today.
4. Add the `hf_xet` extra to huggingface-hub for better performance.
5. Upgrade the `chatml-function-calling` handler with support for reasoning before …
> feat: add support for reasoning tool use and upgrade to Qwen3

- src/raglite/_database.py
- src/raglite/_insert.py
This PR adds front matter to the chunk representation for embedding with the document's filename and/or URL. In the absence of contextual Markdown headings, the front matter can help provide context to the embedder about the chunk.
> feat: add front matter to chunk content

- README.md
- src/raglite/_config.py
- src/raglite/_database.py
- src/raglite/_insert.py
- src/raglite/_query_adapter.py
- src/raglite/_search.py
- tests/conftest.py
- tests/test_rerank.py
This PR simplifies and improves the way vector search ranks chunks.
Before this PR, chunks were (more or less) ranked by descending L1 norm of their multi-vector similarities w.r.t. the query vector. The more relevant sentences in the chunk, the more relevant the chunk becomes. But it also means that the more sentences in the chunk, the more relevant the chunk becomes. On the other end of the spectrum is ranking by the L∞ norm, which means ranking chunks by the similarity of their most relevant sentence to the query vector.
After this PR, chunk are ranked by descending L∞ norm of their multi-vector similarities w.r.t. the query vector.
Changes:
1. In vector search, rank chunks according to the L∞ norm of their multi-vector (cosine) similarities.
2. Remove all vector search metrics except …
> feat: rank chunks by the L∞ norm of their multi-vector similarity

- src/raglite/_search.py
Adding the functionality to the RRF function that we can pass weights to the rankings. This PR doesn't modify the hybrid search function yet to include the option to pass weights, should be done after https://github.com/superlinear-ai/raglite/pull/135 
One other major change to the rrf is done in this PR. Currently, we are assigning a value of 1/(k+len(chunk_id_index)) if a chunk index doesn't appear in the ranking. But I think it makes more sense to treat it as rank = \inf and just give a score of 0, i dont see a reason we would give 'points' for not being in the list. That also simplifies the logic a bit.
See https://github.com/superlinear-ai/raglite/issues/38
> feat: enable weighted reciprocal rank fusion

- src/raglite/_database.py
The md header list would not consistently have length = 6. This caused a list assignment index out of range error
> fix: fix off-by-one error in parsing of Markdown headings

- README.md
- src/raglite/__init__.py
- src/raglite/_config.py
- src/raglite/_eval.py
- src/raglite/_mcp.py
- src/raglite/_rag.py
- src/raglite/_search.py
- src/raglite/_typing.py
- tests/test_rag.py
- tests/test_rerank.py
- tests/test_search.py
This PR makes the search method and all of its hyperparameters configurable by the user.
Changes:
1. Breaking: change the reranker config from a tuple of (language, reranker) pairs to a dict that maps languages to rerankers.
2. Breaking: rename `retrieve_rag_context` to `retrieve_context`.
3. Breaking: rename `create_rag_instruction` to `add_context` [to the user prompt].
4. Introduce a `BasicSearchMethod` Protocol that returns either `(list[ChunkId], list[float])` or `list[Chunk]`.
5. Introduce a `SearchMethod` Protocol that returns what a `BasicSearchMethod` returns or `list[ChunkSpan]`.
6. Introduce a `search_and_rerank_chunks` function to `_search.py` that searches with a given `BasicSearchMethod` and then reranks the results with the configured reranker.
7. Introduce a …
> feat: improve config and API

- pyproject.toml
- tests/conftest.py
- tests/test_chatml_function_calling.py
Changes:
1. Add a slow marker
2. Mark the chatml-function-calling tests as slow
3. Skip slow tests if $CI is set
> ci: skip slow tests in CI

- src/raglite/_database.py
- src/raglite/_search.py
The oversampling in `vector_search` depends on the number of chunklets in the chunk, which itself depends on the chunk size. This PR adapts the oversampling factor as a function of the configured chunk size.
> fix: adapt oversampling to chunk size

- pyproject.toml
- src/raglite/_eval.py
This PR makes pandas an optional dependency. We only need it if you enable the `ragas` extra, so we shouldn't install it by default.
> feat: make pandas an optional dependency

- README.md
- pyproject.toml
Changes:
1. Increase minimum version of Rerankers to v0.10.0, which [fixes an issue with API rerankers](https://github.com/AnswerDotAI/rerankers/pull/65).
2. Upgrade recommended Cohere model to v3.5, which performs significantly better than 3.0 and is multilingual.
> fix: upgrade rerankers and recommended Cohere model

- src/raglite/_eval.py
- src/raglite/_insert.py
- src/raglite/_query_adapter.py
This PR adds a `CHECKPOINT;` after inserting a document into a DuckDB database to ensure that the changes in the WAL are written to the database [1].
[1] https://duckdb.org/docs/stable/sql/statements/checkpoint.html
> fix: run checkpoint after DuckDB inserts

- src/raglite/_query_adapter.py
- tests/test_query_adapter.py
Changes:
1. Use `dataclasses.replace` to set `config.vector_search_query_adapter` to `False` in `update_query_adapter`.
2. Remove the `max_triplets_per_eval` option.
3. Add a passthrough component to the query adapter so that does not affect queries that are not covered by the evals. At the same time, this makes it possible to update the query adapter with only a single eval.
4. Build the query adapter from only a single rank-one update per eval. This reduces the size of the query adapter and has the benefit that all evals contribute (approximately) equally to the query adapter.
5. Optimize the rank-one update per eval to optimally separate positive from negative chunks using a new constrained least squares problem. The solution to this problem simultaneously (a) minimises the impact of …
> feat: optimally separate result sets in query adapter
